# This is a basic workflow to help you get started with Actions

name: Parent Repo CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run sample scripts
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  check-submodule-tests:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the pareent and Submodule repository (including submodule)
      - name: Checkout Parent Repository and Submodules
        uses: actions/checkout@v4
        with:
          # This is crucial for checking out submodules
          submodules: recursive
          # If submodules are private, use a PAT with repo access
          # token: ${{ secrets.YOUR_PAT_TOKEN }}
          # very important, public repo does not require token, however private repo does

      - name: Install Submodule Dependenciies (if any)
        run: |
          cd DockerJenkinsPipeline
          echo I am in the Docker Jenkins Pipeline Child Repo
          echo install dependencies

      - name: Run Submodule Tests
        run: |
          cd DockerJenkinsPipeline
          echo I am running submodule tests
          ./startup.sh
          
